[package]
name = "day12-rust"
version = "0.1.0"
authors = ["xeno"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.3"
